version: '3'

services:
    api-docker-training:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: api-docker-training
        restart: always
        volumes:
            - ./:/usr/src/app
        ports:
            - 3000:3000